// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbqvcyqrykjzcwvxstgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicXZjeXFyeWtqemN3dnhzdGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjYyMzIsImV4cCI6MjA2NTEwMjIzMn0.6ejuh5AnQeysdn_WP6TMLV4hekV8ZNjnbZVPDiRdZfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);